controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

homepage:
    path: /
    controller: App\Controller\HomeController

articles:
    path: /articles
    controller: App\Controller\ArticlesController

categories:
    path: /categories
    controller: App\Controller\CategorieController

admin:
    path: /admin
    controller: App\Controller\AdminController
    
admin_nouveau:
    path: /admin/nouveau
    controller: App\Controller\AdminController::new

admin_editer:
    path: /admin/editer
    controller: App\Controller\AdminController::editer

profil:
    path: /profil
    controller: App\Controller\ProfilController
